apiVersion: cilium.io/v1alpha1
kind: CiliumConfig
metadata:
  name: cilium
  namespace: cilium
spec:
  config:
    ipam: "cluster-pool"
  global:
    endpointRoutes: {enabled: true}
    cni:
      binPath: "/var/lib/cni/bin"
      confPath: "/var/run/multus/cni/net.d"
    prometheus:
      serviceMonitor: {enabled: false}
