apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    name: cilium-olm
  name: cilium-olm
  namespace: cilium
spec:
  replicas: 1
  selector:
    matchLabels:
      name: cilium-olm
  template:
    metadata:
      labels:
        name: cilium-olm
    spec:
      containers:
      - command:
        - /usr/local/bin/helm-operator
        - run
        - --watches-file=watches.yaml
        - --enable-leader-election
        - --leader-election-id=cilium-olm
        - --zap-devel
        - --metrics-addr=localhost:8082
        - --health-probe-bind-address=localhost:8081
        env:
        - name: WATCH_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: RELATED_IMAGE_CILIUM
          value: quay.io/cilium/cilium@sha256:83bfc1052543e8b1e31f06fa2b5bbd2bd41cc79f264010241fc1994e35281616
        - name: RELATED_IMAGE_HUBBLE_RELAY
          value: quay.io/cilium/hubble-relay@sha256:a0769e44299bba301dee08d489f4e2d3b3924916bed985346dcf9fcf10861c8a
        - name: RELATED_IMAGE_CILIUM_OPERATOR
          value: quay.io/cilium/operator-generic@sha256:8a317287b6ac8fe0ba4999342c9627dc913e0c1591552164f96d0aadf5d1a740
        - name: RELATED_IMAGE_PREFLIGHT
          value: quay.io/cilium/cilium@sha256:83bfc1052543e8b1e31f06fa2b5bbd2bd41cc79f264010241fc1994e35281616
        - name: RELATED_IMAGE_CLUSTERMESH
          value: quay.io/cilium/clustermesh-apiserver@sha256:e13d41db3f5ee93d8b3abcaa10cc4005522bc797be3d69fc96ac5e03b60c7b11
        - name: RELATED_IMAGE_CERTGEN
          value: quay.io/cilium/certgen@sha256:0c2b71bb3469990e7990e7e26243617aa344b5a69a4ce465740b8577f9d48ab9
        - name: RELATED_IMAGE_HUBBLE_UI_BE
          value: quay.io/cilium/hubble-ui-backend@sha256:2cf1c7b1fde6161f575f3147c2ef885739e60b8c59a1ed444fe74edbdf22c7c1
        - name: RELATED_IMAGE_HUBBLE_UI_FE
          value: quay.io/cilium/hubble-ui@sha256:c267219946b84f79a5fd2849f5cc71f39453e29d93039e57b9cef2b5802e9c50
        - name: RELATED_IMAGE_HUBBLE_UI_PROXY
          value: docker.io/envoyproxy/envoy@sha256:55a141c0b8e39497b32074cb758b4e5dc2384bd6d9926144969a4452eaa611fd
        - name: RELATED_IMAGE_ETCD_OPERATOR
          value: quay.io/cilium/cilium-etcd-operator@sha256:04b8327f7f992693c2cb483b999041ed8f92efc8e14f2a5f3ab95574a65ea2dc
        - name: RELATED_IMAGE_NODEINIT
          value: quay.io/cilium/startup-script@sha256:1daf817f34000399fcb5da9a94cb299e2810d2c7a52e51de22ba0d4783b6ce84
        - name: RELATED_IMAGE_CLUSTERMESH_ETCD
          value: quay.io/coreos/etcd@sha256:04833b601fa130512450afa45c4fe484fee1293634f34c7ddc231bd193c74017
        image: registry.connect.redhat.com/isovalent/cilium-olm:e04a938a293bcc947c5d0698033ae80af2787803-v1.10.10
        name: operator
        ports:
        - containerPort: 9443
          name: https
          protocol: TCP
        resources:
          requests:
            cpu: 100m
            memory: 512Mi
        volumeMounts:
        - mountPath: /tmp
          name: tmp
      hostNetwork: true
      serviceAccount: cilium-olm
      terminationGracePeriodSeconds: 10
      tolerations:
      - operator: Exists
      volumes:
      - emptyDir: {}
        name: tmp
