apiVersion: v1
kind: Service
metadata:
  labels:
    name: cilium-olm
  name: cilium-olm
  namespace: cilium
spec:
  ports:
    - name: https
      port: 443
      targetPort: 9443
  selector:
    name: cilium-olm
